<%@ Page Title="" Language="C#" MasterPageFile="MPDepartamentos.master" AutoEventWireup="true" CodeBehind="AdministrarDepartamentos.aspx.cs" Inherits="Sistema_de_etiquetas.Departamentos.AdministrarDepartamentos" %>


<asp:Content ID="Content1" runat="server" contentplaceholderid="contenidoPrincipal">
    <h1>Administrar Departamentos</h1>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        </asp:GridView>
    </p>
</asp:Content>



