<%@ Page Title="" Language="C#" MasterPageFile="~/Docentes/MPDocentes.master" AutoEventWireup="true" CodeBehind="AdministrarDocentes.aspx.cs" Inherits="Sistema_de_etiquetas.Docentes.AdministrarDocentes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contenidoPrincipal" runat="server">

    <h2>Administrar Docentes</h2>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        </asp:GridView>
    </p>

</asp:Content>
