<%@ Page Title="" Language="C#" MasterPageFile="~/Docentes/MPDocentes.master" AutoEventWireup="true" CodeBehind="AdministrarDocentes.aspx.cs" Inherits="Sistema_de_etiquetas.Docentes.AdministrarDocentes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contenidoPrincipal" runat="server">

    <h2>Administrar Docentes</h2>
    <p>
        <asp:GridView ID="grdAdministrarDocentes" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="grdAdministrarDocentes_RowEditing" OnRowUpdating="grdAdministrarDocentes_RowUpdating" OnRowCancelingEdit="grdAdministrarDocentes_RowCancelingEdit" OnRowDeleting="grdAdministrarDocentes_RowDeleting">

        </asp:GridView>
    </p>

</asp:Content>
